automatically detect current project

diff --git a/n b/n
--- a/n
+++ b/n
@@ -1,4 +1,7 @@
 #!/bin/bash
+
+target_folder=$(pwd | grep -oP 'repos/\K[^/]+')
+
 cd "$(dirname "$0")"
 source .env
 
@@ -13,6 +16,13 @@ then
 else
     USER_COMMAND=""
 fi
+
+require_target_folder() {
+    if [[ -z "$target_folder" ]]; then
+        echo "Error: You must be inside one of the repos to run this command." >&2
+        exit 1
+    fi
+}
 
 case $1 in
     start)
@@ -58,19 +68,26 @@ case $1 in
         docker exec -it $USER_COMMAND newspack_dev sh -c "/var/scripts/new-site.sh"
         ;;
     build)
-        docker exec -it $USER_COMMAND newspack_dev sh -c "/var/scripts/build-repos.sh $2"
+        if [[ -n "$2" ]]; then
+            target_folder=$2
+        fi
+        docker exec -it $USER_COMMAND newspack_dev sh -c "/var/scripts/build-repos.sh $target_folder"
         ;;
     watch)
-        docker exec -it $USER_COMMAND newspack_dev sh -c "/var/scripts/watch-repo.sh $2"
+        require_target_folder
+        docker exec -it $USER_COMMAND newspack_dev sh -c "/var/scripts/watch-repo.sh $target_folder"
         ;;
     test-php)
-        docker exec -it $USER_COMMAND newspack_dev sh -c "/var/scripts/test-php.sh $2 ${@:3}"
+        require_target_folder
+        docker exec -it $USER_COMMAND newspack_dev sh -c "/var/scripts/test-php.sh $target_folder ${@:2}"
         ;;
     test-js)
-        docker exec -it $USER_COMMAND newspack_dev sh -c "/var/scripts/test-js.sh $2"
+        require_target_folder
+        docker exec -it $USER_COMMAND newspack_dev sh -c "/var/scripts/test-js.sh $target_folder"
         ;;
     composer)
-        docker exec -it $USER_COMMAND newspack_dev sh -c "/var/scripts/composer.sh $2 ${@:3}"
+        require_target_folder
+        docker exec -it $USER_COMMAND newspack_dev sh -c "/var/scripts/composer.sh $target_folder ${@:2}"
         ;;
     db)
         docker exec -it $USER_COMMAND newspack_dev sh -c "wp db cli --allow-root"
